### ISSUE TITLE
more than one page of counters results in multiple layers instead of multiple pages

### ISSUE THREAD

**Issue by jrvjrv** [lifelike/countersheetsextension#10]
I duplicated the three records in bold.csv 17 times for a total of 51 counters. I was using a registration marks length of 20. When I click apply, rather than three pages I get three layers of counters (with 25, 25 and 1 counter(s) on the page), and the exported .pdf has one page only.

If you are considering clearing the layers (as suggested previously), you should also clear the pages.

In the larger picture, perhaps it would be better to have a separate .svg file as the source for the counter templates rather than writing in the counter templates file.

**Comment by jrvjrv** [comment]
Ok, for some reason I missed the multiple .pdf exports of the layers, so my bad. I think it would be nicer if the extension created a single .pdf with separate pages, but this seems to be working.

**Comment by lifelike** [comment]
Unfortunately there is no multi-page support (yet?) in Inkscape, so it has to be layers for now.
