### ISSUE TITLE
Extension Breaks in Inkscape 1.3

### ISSUE THREAD

**Issue by jlr1001** [lifelike/countersheetsextension#101]
I might have over-extended myself a bit here, but I'm guessing in recently did a system update and didn't think about it breaking Countersheet. Any hope for an update to make it compatible with 1.3?

This is the error I'm seeing:

terminate called after throwing an instance of 'Gio::Error'
Traceback (most recent call last):
  File "/home/jlr1001/.config/inkscape/extensions/countersheet.py", line 2247, in <module>
    effect.run()
  File "/usr/share/inkscape/extensions/inkex/base.py", line 250, in run
    self.save_raw(self.effect())
                  ^^^^^^^^^^^^^
  File "/home/jlr1001/.config/inkscape/extensions/countersheet.py", line 1471, in effect
    positions = self.readLayout(svg, suffix)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jlr1001/.config/inkscape/extensions/countersheet.py", line 963, in readLayout
    res.append(self.geometry[c.get('id')])
               ~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'rect669'

That final line references the id of the first rectangle in my cs_layout layer.

Thanks for any help you could offer!

**Comment by lifelike** [comment]
Are you using the latest version? There was a fix for 1.3 a while ago, and I have used it in 1.3 (in FreeBSD). Officially only up to 1.1.1 is supported, but it seems like at least up to 1.3 is still running fine, and I may accept patches to support future versions as well, if Inkscape still can't get their backwards compatibility sorted out.

**Comment by jlr1001** [comment]
Wow. I was under the impression that I had updated the extension since your last update, but I was wrong.

Sorry about unnecessarily raising an alarm. 

Thanks, as always, for creating and maintaining this extension. I still stand by my belief that it's the best custom card/2d component maker out there.

**Comment by lifelike** [comment]
Good to hear and thanks for that comment.
