### ISSUE TITLE
on countersheet_layout layer, clones of rectangles should be used too

### ISSUE THREAD

**Issue by jrvjrv** [lifelike/countersheetsextension#11]
The extension currently finds all rectangles that are direct children of the countersheet_layout layer. Clones, particularly tiled clones, are an easy way to fill a block of identical rectangles that have a regular distribution. If you are laying out a countersheet that has blank areas for sprue, it would be more convenient to clone a single counter rather than having to lay out every individual counter. If you implement this, I believe the first clone overlays the original counter, so for any rectangle that is cloned you would have to ignore the original. Otherwise any changes made on one that was behind would not be visible. The user might move the original too, but it is probably better just to ignore the original of a clone.

**Comment by lifelike** [comment]
You do not have to add a layout rectangle for every counter. One per block of counters on the sprue is enough.

Also a quick way to make tiled copies rather than clomesis to duplicate the object many times (crtrl-d repeatedly) then select all and use the arrange in rows/columns function.

I still think it is a good idea to support clones, but tha it has low prio.

**Comment by jrvjrv** [comment]
> You do not have to add a layout rectangle for every counter. One per block of counters on the sprue is enough.

I do not understand this. If I create a layer called "countersheet_layer" and add four rectangles to it, then in my .csv file I call for 20 repeats, I get five layers (ten for double-sided counters), each with four rectangles, each a duplicate of the countersheet_layer. Is there a mechanism to mark each rectangle on the countersheet_layer as repeated?

**Comment by jrvjrv** [comment]
Ok, I understand this now. The rectangles on the countersheet_layer do not have to be the same size as the counter rectangles. They can be larger, and if multiple counters will fit within a countersheet_layer rectangle, the extension will put them in. It's not an obvious (to me) behavior, but it seems workable.

**Comment by lifelike** [comment]
Now using clones as well as rectangles. All clones is used since that made the fix trivial. In theory you can put clones of non-rectangles in there and get somewhat unexpected results, but don't do that then.
