### ISSUE TITLE
page size other than A4 results in counter positioning errors

### ISSUE THREAD

**Issue by jrvjrv** [lifelike/countersheetsextension#12]
When you change the drawing size to other than A4 (US Legal is a good one to try), for some reason inkscape puts a translation on the layer1 element (transform=translate(0,207.6378)). This extra translation is not caught by the countersheet extension code (as far as I see) and results in the counters being positioned incorrectly (but not the registration marks). This happens whether you change the page size before or after creating the counter artwork. A knowledgeable user can manually edit out the transform using the xml editor, but it is a bit much to expect from an ordinary user.

**Comment by jrvjrv** [comment]
To clarify, the document was created using the default page size (A4), and changing the drawing size was done by document properties. A document created with a template (file, templates...) does not have a translation.

**Comment by lifelike** [comment]
Fixed by jrvjrv's fix merged yesterday, as far as I can tell.
