### ISSUE TITLE
Export to Bitmaps doesn't support paths with spaces

### ISSUE THREAD

**Issue by paulthegreat** [lifelike/countersheetsextension#2]
countersheet.py line 508 should be:
```python
cmd="inkscape -i %s -j -e \"%s\" %s \"%s\"" % (
```
to support directories and file names with spaces.

**Comment by lifelike** [comment]
This is probably correct. I just need to find a few minutes to test that before committing. Thanks!

**Comment by lifelike** [comment]
Fixed!
