### ISSUE TITLE
Adding a padding zero in cs_layer*.pdf filenames

### ISSUE THREAD

**Issue by theclue** [lifelike/countersheetsextension#23]
I've noticed that the filenames of the generated PDFs have only one integer indicating the "page".

i think it would be really useful and easy to implement to add a padding zero on the left of the filename for pages 1 to 9 (ie 01, 02, 03...).

this would allow for an easier automatic ordering of the PDFs when using a command-line tool (like gs) for joining into one PDF simply using *.PDF (instead of manually adding all the components in the correct order.

it would be even better to add an option to specify the filename template in sprintf format, but this would probably be less easier and fast to implement i guess ;)

**Comment by lifelike** [comment]
Good idea! I guess it makes sense to check the total number of sheets and pad as needed.

**Comment by lifelike** [comment]
4-digit names now on master.

This will cause regressions for anyone that has scripts that rely on just being able to enumerate the layers using %d (I know I have for some game(s)) since the id of the layers are affected (that are used to get the filename for exports).
