### ISSUE TITLE
Offsets wrong again with 0.92.1

### ISSUE THREAD

**Issue by lifelike** [lifelike/countersheetsextension#25]
Updated to inkscape 0.92.1 (ubuntu package from inkscape org). Offsets are all wrong and it looks like the 90 vs 96 dpi issue that happened with 0.92, but was fixed.

If an upgrade to 0.92.2 helps will close this as it is impossible to keep support for every patch version when they keep changing how document units and dpi are handled.

**Comment by lifelike** [comment]
It is not unlikely that the error is caused by files being created in 0.91 or older, even if they were modified to 96 dpi in 0.92. Possible workaround to create new file and copy contents from old file.

**Comment by lifelike** [comment]
It works in 0.92.2, but on a different host (and different OS, OSX vs Lubuntu), so not sure if it is fixed because of the newer version or because something else that differ. Not closing until I see correct offsets in 0.92.2 on the Lubuntu host.

**Comment by theclue** [comment]
if this could help I can check with the new release this evening

kr,
g.
