### ISSUE TITLE
Missing Images in Examples

### ISSUE THREAD

**Issue by nsmaree** [lifelike/countersheetsextension#27]
Good day.  I get an error saying "Unable to find rectangle with id 'unit' that was specified in the CSV data file."  Are there perhaps some files missing from the Examples folder?

**Comment by lifelike** [comment]
Hi,

Do you have the correct SVG open in Inkscape when you run the generator?
The file counters.svg is probably the one (if I guess correctly that you
are trying to use one of the counters.csv or counters-2-sided.csv files?).

**Comment by nsmaree** [comment]
Sorry, I missed that you needed to open the SVG file before running the extension.  Thanks for your swift response!

**Comment by lifelike** [comment]
Closing this, but really need to do something about documenting that part much better.
