### ISSUE TITLE
Semi-colon in text field acts like comma

### ISSUE THREAD

**Issue by paulthegreat** [lifelike/countersheetsextension#3]
When importing a CSV field with a semi-colon that isn't surrounded by quotes, the resulting output is as if the semi-colon was a comma. According to Python documentation, line 612 modified slightly to
```python
reader = csv.reader(open(datafile, "rb"), delimiter=',')
```
should work fine, but Inkscape gives me an error saying csv.reader is not expecting another parameter. Also, according to Python documentation, ',' should be the default delimiter. Is this an old version of Python that is being installed with Inkscape on Windows that's causing problems?

**Comment by lifelike** [comment]
The code in the extension tries to guess if ; or , are used, because some application(s) output ;-separated fields when you generate a csv. It isn't ideal and the heuristics can/should probably be improved, but I don't think forcing it to use commas is a good solution.

**Comment by paulthegreat** [comment]
Unfortunately, both Excel and Google Sheets fail to quote semicolons when saving as a CSV, which means having to manually adjust any fields that have semicolons in them. I just don't understand why the standard python library is behaving differently than specified in documentation. Oh well.

**Comment by lifelike** [comment]
I figured THAT out at least: cvs.reader is a helper-function I defined, confusingly not the standard python csv-reader. If you just use the default python reader it fails to parse csv files separated with semi-colons (or at least that was my conclusion about 7 years or so when I wrote that code). I don't remember if it was OpenOffice or Excel or some other tool that defaulted to semi-colons when you exported a sheet (despite that it makes no sense to use anything but commas when the user asks to export to a comma-separated file...).

**Comment by lifelike** [comment]
I removed the old csv-module and changed the code to use the real Python csv-module instead. It seems to work (with a little help from csv.Sniffer). Added tests to verify this as well.

The old csv.py and csv.pyc must be removed or the extension will crash. Attempted to add a warning text, but I guess no one will read that anyway.

**Comment by paulthegreat** [comment]
Cool, thanks so much! (Also, somehow I missed your earlier comment on this thread until now.)
