### ISSUE TITLE
Option function not working

### ISSUE THREAD

**Issue by nsmaree** [lifelike/countersheetsextension#33]
Good day

I am trying to use the **Option** function to show some images on some cards but not on others.  I get the following error if I use anything other than y, yes or x to indicate that an image should NOT be shown.  Your examples work fine, but I cannot duplicate the results on my own cards:

Traceback (most recent call last):
  File "countersheet.py", line 1914, in <module>
    effect.affect()
  File "inkex.py", line 283, in affect
    self.effect()
  File "countersheet.py", line 1275, in effect
    positions[box].y+rowy)
  File "countersheet.py", line 727, in generatecounter
    if not c.is_included(eid):
  File "countersheet.py", line 107, in is_included
    if fnmatch.fnmatchcase(eid, eglob):
  File "C:\Program Files\Inkscape\lib\python2.7/fnmatch.py", line 83, in fnmatchcase
    return re_pat.match(name) is not None
TypeError: expected string or buffer

Thanks for the effort and for keeping this project alive!

**Comment by lifelike** [comment]
Sorry I have not had time to look much into this. I  can not see anything obvious. Guess some sanity-checks could be added to that function and that might fix this, but it might also introduce some new bug. Some example failing would be very useful to make sure the correct thing is fixed. Could be a symptom of something that should be fixed (also) somewhere else. (But I guess a few checks in that function will be a good thing to have anyway, so I can add that.)

**Comment by nsmaree** [comment]
Thanks for the effort.  I'll rebuild the whole SCV.  Perhaps I have some luck with that.  Awesome add-on by the way.  A real lifesaver to prototype some games
