### ISSUE TITLE
Font changed to 'sans' from bold or italic until end of line

### ISSUE THREAD

**Issue by fractalpixel** [lifelike/countersheetsextension#34]
I'm trying to use a custom font for a multi-line text area that has input text containing words in bold and italics.  

However, the font changes to the default sans-serif font from the first bold or italic word on a line until the end of line, then the next line starts with the font I set for the text area again.

For example here I selected Courier as the font, it gets switched to sans as soon as \*bold\* or /italics/ is encountered on a line:
![image](https://user-images.githubusercontent.com/40071864/44682111-313ab400-aa4b-11e8-92ba-e88c5b4442e7.png)

**Comment by lifelike** [comment]
Can you try the latest master version and see if that works better? (Use the download zip link on GitHub or use git.)

Added a workaround that unfortunately is not likely to cover all possible cases. Just copying the style from the top of the multiline text (i.e. the spanRoot element) to all parts that should not have any special style added. So I can imagine there are ways it can break, especially if someone is very creative in setting styles on the text element, or setting the style in a parent group or something that is probably legal to do in the XML but probably not possible to do from Inkscape's GUI.

**Comment by fractalpixel** [comment]
Thanks for the quick fix!

It works better now (switching to the correct font for non-bold and non-italic text works), but it still uses the default sans-serif font for the bold text, instead of the font specified for the text element.  Weirdly, italics seems to sometimes work, but inconsistently (see picture, I changed the font for the text area to a medieval-style one).
![image](https://user-images.githubusercontent.com/40071864/44713792-8662de00-aabc-11e8-8a7c-dc9923e6a6b5.png)

**Comment by fractalpixel** [comment]
I had a look at the code and fixed the issue, see pull request #37.

**Comment by lifelike** [comment]
I was thinking something like that had to be done. Great that you could fix it instead of waiting for me to get around to do it! Many thanks!
