### ISSUE TITLE
Support UTF-8 encoded CSV

### ISSUE THREAD

**Issue by FranciscOntV** [lifelike/countersheetsextension#48]
I'm trying to create a countersheet with `Ñ` & `ñ` characters in the source CSV, however if the CSV is encoded with ANSI, the extension throws an error and is unable to create the countersheet, also if the CSV is encoded in UTF-8 the extension can't even find the rectangle by Id.

**Comment by lifelike** [comment]
Thanks for this feedback, but going to need more details. There is already UTF-8 support and some included examples/tests use it, so it can not be entirely broken (although there might be edge-cases that breaks?). A small example showing what does not work would help.

If it has something to do with the id of rectangles, you should know that SVG (the format used by Inkscape) only allows ASCII symbols (and only a small subset even of those, like letters and digits and a few more symbols) so you can never use ASCII ids on the rectangles. (If Inkscape allows you to set the id to something that is not a valid id that should be reported as a bug in Inkscape).

https://www.w3.org/TR/SVG2/struct.html#Core.attrib
https://www.w3.org/TR/xml/#NT-Name

**Comment by danielgasparpereira** [comment]
Hola. Me ocurre algo parecido importando un texto en el counter con el formato **<<textfile.txt** . El texto incluido en el archivo .txt contiene letras con acento como "á, é í ó ú" además de la "ñ Ñ". Al eliminar las letras con acento, el texto se inserta correctamente. El problema ocurre al aparecer algún caracter de los indicados. Es un problema para los que trabajamos en español. En mi caso tengo Inskscape 0.92.4 para Windows 64bit.

**Comment by lifelike** [comment]
This is hopefully fixed now. I have not tested every possible place that strange utf-8 characters can exist, but it works for selecting templates to use and for <<textfile.txt file input. Please let me know if it is still missing somewhere.

**Comment by tripmine253** [comment]
Linux Solution: 
`file -i cards.csv`
> cards.csv: text/plain; charset=utf-8

`iconv -f UTF-8 -t ASCII//IGNORE cards.csv | tee  cards2ascii.csv`

**Comment by lifelike** [comment]
Python script assumes all input files are UTF-8.
