### ISSUE TITLE
Call to os.popen3 on line 441 causes error on Windows, Inkscape 0.91

### ISSUE THREAD

**Issue by kelnage** [lifelike/countersheetsextension#5]
When I ran the script with the "bold" example, I got an error message about the call to os.popen3 on line 441, saying that 'r' is an illegal parameter. Checking the Python 2 documentation, it seems on Windows that the mode should be either 'b' (for binary data) or 't' (for text data), whilst POSIX OSs ignore it completely.

See the Python 2 documentation here: https://docs.python.org/2/library/os.html#os.tmpfile

**Comment by lifelike** [comment]
Thanks! Did nod test on Windows. Fixed by changing to 't'.
