### ISSUE TITLE
Support Inkscape 1.0

### ISSUE THREAD

**Issue by lifelike** [lifelike/countersheetsextension#54]

**Comment by ernierasta** [comment]
Thank you for working on that (I saw dedicated branch)! My distro updated Inkscape to 1.0 recently and I have no easy way to downgrade, so I am very glad this extension seem to survive transition to 1.0. 

Thank you for your great work and very useful extensions!

**Comment by hhllcks** [comment]
Hey, any progress on this?
Since inkscape 0.9 is 32bit it does not run on MacOS Catalina.
But Countersheets does not work with inkscape 1.0

So I can't upgrade my mac right now because of this. Otherwise I can not generate my cards ...

Or is there a workaround to get this running on Catalina?

**Comment by lifelike** [comment]
I have had the opposite problem of not being able to run Inkscape 1.0 (and my only Mac is too old to upgrade to Catalina), but I have 1.0 running in Linux now, so there is hope that the extension will work soon. It currently does not unfortunately, even with the changes on the support_inkscape_1.0 branch.

**Comment by lifelike** [comment]
Seems like text work fine on the support_inkscape_1.0 branch, but images are broken (any image filename with a relative path has file:///tmp/ prefix added for some unknown reason).

**Comment by lifelike** [comment]
PDF export is broken too. Inkscape gets stuck and has to be killed if I attempt to set a PDF export directory.

**Comment by lifelike** [comment]
Pushed a version that fixes images.

There is a new parameter to set when running the effect, called "Image Path". It must be set to the folder (i.e. directory) where your images are (if not using absolute paths for image filenames). This is required to add paths that (I can get to) work in Inkscape 1.0. A nice side-effect is that previously it was a bit non-obvious exactly what it meant if you just said "image.png" in a spreadsheet. Now you have to specify exactly what that means.

This has to be properly documented of course. I do not know if it will be a permanent solution. Currently the image path is mandatory, because not setting it will result in all images being broken (unless you put absolute paths in the spreadsheet, but who does that?).

**Comment by lifelike** [comment]
It looks like PDF exports works randomly. It  does not look as if my computer is running out of RAM or anything else obvious, but sometimes it looks like the effect is just stuck when trying to export a PDF and I have to kill Inkscape. At other times it works as intended. Not sure if it is a bug in this extension or in Inkscape itself.

**Comment by ernierasta** [comment]
Thank you! I have just tested it with example "cards.svg" and all is working great - including *Save a copy* to pdf file. Great work. I personally do not mind pointing it to image directory, IMHO it can stay like that.

Have a great day!

**Comment by lifelike** [comment]
Good to hear!

PDF and PNG exports seem to work now. @jamis left a comment in the code saying what to do, so there really was not much of a mystery to solve (use communicate, not wait).

Inline images are slightly off, but that can be tracked as a new issue. Going to tag this as a new alpha-release or something in a few minutes.

**Comment by lifelike** [comment]
Inline images seem to be off because Inkscape 1.0 has some issues with rendering some unicode characters(?). Implemented workaround (using capital letter X instead of funny BIG BLACK SQUARE unicode symbol as placeholder for inserting icons). Might require some tuning to get position good enough.

Closing this after merge to master and probably some update to README to redirect users of older Inkscape versions to the previous extension version.

**Comment by hhllcks** [comment]
Thank you! 

Will it be merged soon or should I test with this branch?

**Comment by lifelike** [comment]
Unless someone notices something horribly broken, I plan to merge this to master and make a new release (3.0?) this weekend. It would be very useful to hear from more that the branch seems to work before I merge it to master.

**Comment by lifelike** [comment]
Merged this to master! Thanks everyone!
