### ISSUE TITLE
Text markup not working

### ISSUE THREAD

**Issue by louiskehlet** [lifelike/countersheetsextension#57]
I cannot get text markup to work, either from my .csv file or from an imported .txt file using <<filename.txt.

The markup syntax is also defined in two different ways in the pop-up box and on the wiki set text page. I have tried either option and have not had any luck.

**Comment by lifelike** [comment]
Need to know more to guess what is not working.

Will look into the different syntaxes to make sure they are both correct. Thanks for pointing that out!

**Comment by lifelike** [comment]
Closing this unless more information is added.
