### ISSUE TITLE
Error in Loading Counters.csv

### ISSUE THREAD

**Issue by DagobertBrandt** [lifelike/countersheetsextension#61]
Trying to walk through the tutorial.  Have all install get this message when trying to load counters.csv

Unable to find rectangle with id 'unit' that was specified in the CSV data file.

Seems to start to load, but then, after about 3 mins, returns error

Inkscape version .092

**Comment by DagobertBrandt** [comment]
I sorted it out.

**Comment by joshi0212** [comment]
how did you figure it out? I have the same problem
