### ISSUE TITLE
Cutting (registration) marks possition

### ISSUE THREAD

**Issue by ernierasta** [lifelike/countersheetsextension#65]
Hi Pelle!
I am experimenting with your excellent extension, and as you noted on BGG - there is no way influence placement of cutting marks. 

Maybe even simply putting cutting marks under bleed is simple and good solution?

I tried to put it back with cs_regstyle, but it has no effect.

BTW: Cutting marks behaves good for backs when I enable them, but they are on top of fronts bleed.

**Comment by lifelike** [comment]
I do not think simply hiding the lines behind the bleed is enough. It makes sense to be able to add a distance between the lines and the artwork even when not using bleed. I think adding an option for this would be better.

cs_regstyle only works for setting the line attributes like color and dashes used for the lines etc.

**Comment by ernierasta** [comment]
Yeah, you are probably right, that it would be more correct approach.

If you create white bleed hiding would work, but ability to define distance would be also definitely more user friendly.
