### ISSUE TITLE
Can't set an input file

### ISSUE THREAD

**Issue by yumimuff** [lifelike/countersheetsextension#75]
I installed the extension (pasting the two files on the extensions folder) but when I tried to use it for the first time there was no "Data file (CSV):" option. Any idea on why this is happening?
To clarify: I can see the Boardgames extension on the menu, and I can open the "Create a countersheet" box, but when it opens, there's no way to put the name of the input CSV file.
![image](https://user-images.githubusercontent.com/86863158/124341126-e7219780-db7f-11eb-82b2-0c48d13e3a94.png)

**Comment by lifelike** [comment]
I never saw that, but since Inkscape before version 1.0 did not support
file inputs my guess is that you need a newer Inkscape (or older extension).
