### ISSUE TITLE
bold.csv/bold.svg example does not work

### ISSUE THREAD

**Issue by jrvjrv** [lifelike/countersheetsextension#8]
It is able to replace card-title & card-image, but card-bold returns the message "Failed to put substitute text in 'card-bold'". I think there is a missing return statement in substitute_text. The card-bold element has the text on it. The code in substitute_text replaces it, but without the return statement it goes through all the children too via setFirstTextChild, and card-bold has no children.

    def substitute_text(self, c, t, textid):
        for glob,subst in c.subst.iteritems():
            if fnmatch.fnmatchcase(textid, glob):
                if t.text:
                    t.text = subst
                    # ******************************** BEGIN ADDED RETURN HERE **********************************
                    return
                    # ******************************** END ADDED RETURN HERE **********************************
                if (t.tag == inkex.addNS('flowRoot','svg')
                    and subst.find("\\n") >= 0):
                    self.setMultilineText(t, subst.split("\\n"))
                elif not self.setFirstTextChild(t, subst):
                    inkex.debug( "substitute_text " + subst + " " + textid )
                    sys.exit("Failed to put substitute text in '%s'"
                             % textid)
                if c.id:
                    t.set("id", textid + "_" + c.id)

**Comment by lifelike** [comment]
Good catch! Sorry for the late response. I change from if to elif to make sure only one of the branches are executed and now the bold example works. Ought to make all examples run as part of the svgtests some day to avoid silly regressions like this one.
