### ISSUE TITLE
Inline image adds line spacing

### ISSUE THREAD

**Issue by josemigallas** [lifelike/countersheetsextension#84]
I'm having trouble adding inline images in text. It should be as simple as adding `{image_name.ext}` to the text, isn't it? And the image size I'm using is the same as the ones in `countersheetextension/examples`.
Here's how it's rendered:
<img width="326" alt="Screenshot 2022-04-11 at 10 08 55" src="https://user-images.githubusercontent.com/11672286/162698283-d0265941-b97d-4fe7-aa5d-bc5daf34e58a.png">

When rendered in its own line it looks  g
![Screenshot 2022-04-11 at 10 36 23](https://user-images.githubusercontent.com/11672286/162698396-ea53861f-0294-4fb6-967f-f044c04cc4a8.png)
ood enough (although it looks like there's still some space added before the line):

Any ideas or suggestions?

**Comment by lifelike** [comment]
How do you add the icons in multiple lines of text? Are those multiple one-line text elements?

@ernierasta claimed some success with inserting icons in multiple lines of text, but I have not managed to get it to work and the documentation (i.e. wiki) still says it is not supported. Inserting icons in one-line text elements should work though (like in prototype_cards.svg with the **linecard** template for instance).

**Comment by josemigallas** [comment]
@lifelike yeah.. I was inserting them in multiline text elements, I didn't realize the example uses 3 one-line text elements. It's not ideal but I made it work.
Interestingly enough, in the second image, the icons don't look too bad even when it's a multiline text element.

Closing this now. Thanks!
