### ISSUE TITLE
Centering of multiline text

### ISSUE THREAD

**Issue by Francis-42** [lifelike/countersheetsextension#85]
Just getting started with the extension, I'm finding it extremely useful and powerful.

However, I encountered the following issue. I am using a multi-line text object with text alignment set to centred. When I now insert text with linebreaks using \n, it defaults back to left-aligned text.
Is there any way to combine multi-line text objects and manually set line breaks while retaining a set text alignment?

**Comment by lifelike** [comment]
Closing this as I believe it is fixed now. Hopefully it did not break anything else. All style set on flowed text was lost, not only alignment.
